# Training {#sec-training}

```{r setup, echo=FALSE, results="asis"}
library(rebook)
chapterPreamble()
```

The page provides practical information to support training and self-study.

## Checklist {#sec-checklist}

Brief checklist to prepare for training (see below for links).

- Install the recommended software

- If the time allows, watch the short online videos and familiarize yourself
with the other available material

- Join Gitter online chat for support

## Recommended software {#sec-software}

We recommend installing and setting up the relevant software packages on
your own computer as this will support later use. The essential
components to install include:

- [R (the latest official release)](https://www.r-project.org/)

- [RStudio](https://www.rstudio.com/products/rstudio/download/);
choose "Rstudio Desktop" to download the latest version. Check the
[Rstudio home page](https://www.rstudio.com/) for more
information. RStudio is optional.

- Install key R packages (Section [@sec-ecosystem] provides an
installation script)

Once you've successfully installed the software, consider exploring examples
from Section [@sec-exercises] even before starting the training. Running the
workflows is easy — just copy and paste the examples. You can then try
additional examples from the book, adapting and applying the techniques to your
own data. Source code for each chapter is available on
[Github](https://github.com/microbiome/OMA).

## Study material {#sec-material}

We encourage you to familiarize yourself with the material and test examples
in advance but this is optional. If you're new to this topic, the following
resources may be particularly helpful.

- [Interactive R tutorials for beginners](https://rstudio.github.io/learnr/articles/examples.html)

- [Introduction to R](https://noppe.2.rahtiapp.fi/main/catalog) (available in CSC Noppe, see [@sec-vm])

- [Introduction to data analysis with R and Bioconductor](https://carpentries-incubator.github.io/bioc-intro/) (for beginners with R)

- [Short online videos](https://www.youtube.com/playlist?list=PLjiXAZO27elAJEptP59BN3whVJ61XIkST) on microbiome data science with R/Bioconductor

- [Quarto presentations](https://microbiome.github.io/outreach/index.html)

- [Orchestrating Microbiome Analysis with Bioconductor (OMA)](https://microbiome.github.io/OMA/) (this book)

- [Other outreach material](https://github.com/microbiome/outreach)

- @sec-exercises for self-study

- @sec-resources and links to complementary external material

## Virtual machines and learning environments {#sec-vm}

In most of the training courses, we use learning environments that have
necessary software installed. Check from course details, if this applies to the
course that you are participating.

In most training courses, we use learning environments with the required
software pre-installed. Please check the course details to see if this applies
to your course (you can get the join code from course organizers).

- CSC Noppe (formerly Notebooks) is available for users with accounts at Finnish
higher education institutions or state research institutes. For more
information, visit
[this page](https://docs.csc.fi/cloud/noppe/guide_for_students/).

- [Bioconductor workshops](https://workshop.bioconductor.org/) are accessible
with a Bioconductor account, providing pre-installed Bioconductor software and
workshops.
